### ISSUE TITLE
Resizing icons

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#431] opened 2021-11-21 10:47 UTC
1) Summary:
Resizing icons
2) Description:
If you change the image, go to the "View" tab, select the "Icon size" item, put a checkbox for a different size, then the warning window "Request to exit" will open and the program will offer to save the image. After clicking on the "Cancel" button, we return to the main window. Go to the "View" tab again, select the "Icon size" item, you can see that the checkbox is on a different size, but the size of the icons has not changed. If you restart the application, the size of the icons will change.
 3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- change image
- go to the "View" tab
- select the item "Icon size"
- put a checkbox on a different size of icons (a warning window "Request to exit" will open)
- click the "Cancel" button.

5) Expected behavior
The checkbox is at the same size and the size of the icons does not change.
6) Actual behavior
The checkbox is on a different size, but the size of the icons does not change.
7) Attachment:
 
![24](https://user-images.githubusercontent.com/94738204/142758771-60561853-e8f4-45c2-aff0-93e55b63d5ce.png)

8) Severity - Major
9) Priority- High

**Comment by circular17** [comment] 2021-11-27 17:02
fixed on dev

**Closed by circular17** 2021-11-27 17:02 UTC

**Comment by circular17** [comment] 2022-06-04 19:37
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/319
