### ISSUE TITLE
Color of menu bar is white when dark theme is selected

### ISSUE THREAD

**Issue by diatarveden** [bgrabitmap/lazpaint#504] opened 2022-03-29 11:57 UTC
**Description:**

> The menu bar should change color to dark, when the dark theme selected

**Step of reproduction:**

> 1. Open LazPaint
> 2. Go to ''View'' -> ''Dark theme''

**Expected result:**

> The entire program interface has a dark design

**Actual result:**

> Menu bar has a white design

**Environment:**

> Windows 10 x64, Build 19042.1586, Version 20H2
> LazPaint 7.1.6, 64-bit

**Severity:**

> Trivial

**Priority:**

> Medium

**Attachment:**

![image](https://user-images.githubusercontent.com/102584378/160605848-6fef831d-278e-4f03-be6a-f511b32ddbe3.png)

**Comment by circular17** [comment] 2022-05-27 12:12
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/378

**Closed by circular17** 2022-05-27 12:12 UTC
