### ISSUE TITLE
Incorrect display of the image when pressing the ‘Paste' button.

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#404] opened 2021-11-20 13:43 UTC
Priority: MINOR

Environment: MacOS Big Sur 11.5.1(20G80), LazPaint 7.1.6 (64-bit)

Description:
The user presses ‘Paste’/‘Paste as new image’/‘Paste as new layer’ buttons and receives an incorrect image.

Steps to reproduce:
1.Select any image on the device that fits the format of the LazPaint (lzp, ora, pdn, bmp, gif, ico, cur, jpg, jpeg, pcx, png, psd, tga, tif, tiff, xpm, xwd) and copy it.
2.Open the LazPaint;
3.Click on the button ‘Edit’ on the top panel of the app;
4.In the menu that appears, choose the ‘Paste'/‘Paste as new image’/‘Paste as new layer’ buttons.

Actual result: The content of the image is not displayed and the scaling is incorrect on the existing layer.

Expected result: The user receives a correctly displayed and scaled image by clicking ‘Paste’/ ‘Paste as new image’ on the existing layer. The user receives a correctly displayed and scaled image by clicking ‘Paste as new layer’ on the new layer.

https://user-images.githubusercontent.com/65169031/142728536-460ee9e6-9e9d-468b-81f0-1547d615dbc4.mov

**Comment by circular17** [comment] 2022-06-04 18:09
Thanks for the report.

Duplicate of https://github.com/bgrabitmap/lazpaint/issues/339

**Closed** 2022-06-04 18:09 UTC
