### ISSUE TITLE
Changing brush size by "alt+mouse scroll" doesn't show the brush size and moves keyboard focus to the menu bar

### ISSUE THREAD

**Issue by sergvpt** [bgrabitmap/lazpaint#463] opened 2021-12-19 12:42 UTC
**Severity** Minor

**Description**
While you are changing brush size by "alt+mouse scroll" brush cursor keeps its size and keyboard focus moves to the menu bar

**Steps to reproduce**
1. Choose a brush tool
2. Move it to canvas
3. Hold Alt button and scroll mouse

**Expected result**
Brush cursor shows new size of the brush

**Actual result**
The brush cursor freezes at the current size and keyboard focus moves to the menu bar

**Environment:**
Windows 10 Build 19043.1415 Version 21H1,
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/96376876/146675178-6f641daa-9b3a-4f08-a9fc-6f37c54f9ec6.mp4

**Comment by circular17** [comment] 2022-06-04 07:26
Indeed when pressing ALT it activates the menu on Windows.

**Comment by circular17** [comment] 2022-06-04 20:10
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/305

**Closed by circular17** 2022-06-04 20:10 UTC
Labels: bug
