### ISSUE TITLE
File > Open dialog too wide when not using Image Browser

### ISSUE THREAD

**Issue by circular** [bgrabitmap/lazpaint#511] opened 2022-06-25 00:21 UTC
Hi, thanks for all your work on LazPaint, it's been fun to use.

On my system there seems to be an issue with the File > Open dialog, when "Use image browser" is unchecked in the File menu. 

It seems that the number of RAW file extensions (30+ ... *.3fr, *.ari, *.arw, etc.) is causing the regular File > Open dialog to expand to somewhere around 2000 pixels wide. This window cannot be resized on my system. Thanks for looking into it.

**Comment by lainz** [comment] 2022-06-25 00:28
That's for sure a Windows bug with the file explorer. Which version of windows you're using and do you have checked the explorer option to hide fille extensions or not ?

**Comment by circular** [comment] 2022-06-25 00:37
> That's for sure a Windows bug with the file explorer. Which version of windows you're using and do you have checked the explorer option to hide fille extensions or not ?

Thanks for getting back to me. I am feeling a bit conflicted now, because the system swears it is using Ubuntu 20.04. :-) Just to avoid any misunderstanding I'm including a screenshot.

https://i.postimg.cc/DyfF62QT/lazpaint.png

Is there an option to hide file extensions even if I'm not using Windows? I'm open to any workarounds.

**Comment by lainz** [comment] 2022-06-25 01:54
I've seen this bug on Windows for that I assumed that OS..

For the moment use the lazpaint file explorer. Is good enough to navigate between folders. Is not as intuitive as the OS default but it works.

**Comment by circular17** [comment] 2022-06-25 17:30
For a moment I though I had answered this conversation and did not remember. 😄

**Comment by circular17** [comment] 2022-06-25 17:31
I think it is a duplicated of https://github.com/bgrabitmap/lazpaint/issues/249

**Comment by circular17** [comment] 2022-06-25 17:32
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/249

**Closed** 2022-07-22 15:44 UTC
