### ISSUE TITLE
No save prompt when opening new image via drag and drop

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#456] opened 2021-12-18 11:51 UTC
**Severity**
Major

**Defect descirption**
No prompt to save changes is displayed when opening new image via drag and drop

**Steps to reproduce**
- Open and modify an image 
- Drag and drop another image into the editor

**Expected result**
Save prompt asks if one wishes to save the changes before opening another image

**Actual result**
No save prompt is displayed, no undo option either

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/84194921/146639949-2cd6abd3-8684-42d4-8353-3353737c9597.mp4

**Comment by circular17** [comment] 2022-05-29 19:18
fixed on dev

**Closed by circular17** 2022-05-29 19:18 UTC

**Comment by circular17** [comment] 2022-06-04 20:22
duplicate of https://github.com/bgrabitmap/lazpaint/issues/299
