### ISSUE TITLE
When switching to a dark theme, the top menu of the application does not change the style.

### ISSUE THREAD

**Issue by Gos1k** [bgrabitmap/lazpaint#378] opened 2021-11-03 08:31 UTC
**1) Summary:** When switching to a dark theme, the top menu of the application does not change the style.

**2) Description:** When switching to a dark theme, the top menu of the application does not change the style, it should change too.

**3) Environment:**

 Windows 10 Pro x64, Build 19043.1320, Version  21H1
LazPaint 7.1.6, 64-bit, portable
 
**4) Steps to reproduce**

Press View
Press Dark theme

**5) Expected behavior**
App style color should change

**6) Actual behavior**
The top menu of the application does not change its color

**7) Attachment:**
![image](https://user-images.githubusercontent.com/93593291/140029298-d82044f7-3ef8-4ee4-a5c4-6f553c0c8ced.png)

**Comment by circular17** [comment] 2021-11-05 08:09
Yes, the menu and title are rendered by the system. This won't be fixed soon. Maybe you can choose a dark mode at the OS level?

**Comment by circular17** [comment] 2022-06-04 22:06
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/121

**Closed by circular17** 2022-06-04 22:06 UTC
Labels: enhancement, low priority
