### ISSUE TITLE
Changes to the language version of the application

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#430] opened 2021-11-21 10:46 UTC
1) Summary:
Changes to the language version of the application
2) Description:
If you change the image, go to the "File" tab, select the "Language" item, put a checkbox for another language, then a warning window "Request to exit" will open and the program will offer to save the image. After clicking on the "Cancel" button, we return to the main window. Again, go to the "File" tab, select the "Language" item, you can see that the checkbox is in a different language, but the language has not changed. If you restart the application, the language will change.
 3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- change image
- go to the "File" tab
- select "Language"
- put a checkbox on another language (a warning window "Request to exit" will open)
- click the "Cancel" button.

5) Expected behavior
The checkbox is in the same language and the language does not change.
6) Actual behavior
The checkbox is in a different language, but the language does not change.
7) Attachment:
![23](https://user-images.githubusercontent.com/94738204/142758587-b880407a-f7f1-417a-b38e-f602637cc146.png)

8) Severity - Major
9) Priority- High

**Comment by circular17** [comment] 2021-11-27 16:48
fixed on dev

**Closed by circular17** 2021-11-27 16:48 UTC

**Comment by circular17** [comment] 2022-06-04 19:50
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/288
