### ISSUE TITLE
Unable to cancel "Paste as new image' action

### ISSUE THREAD

**Issue by AlexeyMischuk** [bgrabitmap/lazpaint#351] opened 2021-10-27 05:17 UTC
### Description
"Undo" function doesn't work after using "Paste as new image". This action have very similar keyboard shortcut with "Paste as new layer" (Ctrl-Alt-V and Shift-Ctrl-V), it's easy to mix them up and to lose all work progress.

### Environment
Windows 10 Pro 64-bit (18362.356)
LazPaint 7.1.6 (64-bit)

### Reproduction steps
- Open any image
- Select rectangular zone lesser than original image (Select → Select rectangle)
- Press Ctrl-C
- Press Ctrl-Alt-V ("Paste as new image")
- Press Ctrl-Z

### Actual result
"Undo" function doesn't work

### Expected result
"Undo" works correctly and resumes previous picture

**Comment by circular17** [comment] 2022-06-04 19:01
related to https://github.com/bgrabitmap/lazpaint/issues/101

**Comment by circular17** [comment] 2022-06-04 19:02
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/377

**Closed by circular17** 2022-06-04 19:02 UTC
Labels: enhancement, low priority
