### ISSUE TITLE
The program window is minimized to the background

### ISSUE THREAD

**Issue by AntoninaManzhela** [bgrabitmap/lazpaint#356] opened 2021-10-27 11:12 UTC
**Description**
When you close the "texture editing" window, the working window of the program is minimized and switches to another application window.

**Environment**
Windows 10 64-bit
LazPaint 7.1.6 (64-bit)

**Steps to reproduce**
1 open a file or create a new one
2 elect the texture mapping tool
3 Select texture preview on the top toolbar
4 click on the "validate modifications" button in the texture editing window

**Expected result**
The texture editing window is closed. The main program window is open.

**Actual result**
The texture editing window is closed. The main program window is minimized, a window of another program opens.

https://user-images.githubusercontent.com/93258577/139055010-874f064b-4321-4239-ac7f-c8fe8a55169d.mp4

**Comment by circular17** [comment] 2022-06-04 18:57
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/418

**Closed by circular17** 2022-06-04 18:57 UTC
