### ISSUE TITLE
file open with Ctrl + O (perhaps again) yields a widget too wide

### ISSUE THREAD

**Issue by nbehrnd** [bgrabitmap/lazpaint#547] opened 2023-05-26 08:34 UTC
## background

+ related to an earlier post [here](https://github.com/bgrabitmap/lazpaint/issues/249) about Lazpaint 7.1.6, and possibly [here](https://github.com/bgrabitmap/lazpaint/issues/511)
+ Lazpaint version:  7.2.2 64bit as provided as package lazpaint-gtk2 (7.2.2.2) by Debian's servers
+ Operating System: Linux Debian 12/bookworm 64 bit (at present branch testing, kernel 6.1.0.9-amd64) with Xfce4 (4.18) and GTK (3.24.37) desktop environment

## what happens

+ it seems impossible to horizontally shrink / decrease the width of the widget to a dimension more practical (interestingly, further *increase* of the widget's width is possible though)
+ instead the width of the widget appears to default to be about twice as wide as the screen at disposition (1280 x 800 px, for example)
+ the import of the .png in question however is working fine

  ![report](https://github.com/bgrabitmap/lazpaint/assets/19709084/0a3aa137-d467-4ed5-9ed8-f803685822a2)

**Comment by circular17** [comment] 2023-05-26 10:59
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/249

**Comment by circular17** [comment] 2023-05-26 11:00
The package may not contain yet the fix of the LCL. It can take time before it is actually used in published versions.

**Closed by circular17** 2023-05-26 10:59 UTC

**Comment by nbehrnd** [comment] 2023-05-26 12:11
By June 15th, 2022, thread 249 indeed contains the statement

> Fixed on Linux as well.

However thread 249 (starting by September 3rd, 2021) referred to LazPaint 7.1.6.  This is why I speculated (and perhaps erred) the cause could be related, though a different one to the in my report for LazPaint 7.2.2 filed today, May 5th, 2023.

**Comment by circular17** [comment] 2023-05-26 17:00
Yes, well hopefully it will be fixed in the LCL by the next release.
