### ISSUE TITLE
The text on the button does not fit on the button in the print window in the Russian version.

### ISSUE THREAD

**Issue by Tivotar** [bgrabitmap/lazpaint#358] opened 2021-10-27 14:58 UTC
**Severity**: Minor.
**Priority**: Medium.
**Description**: The inscription on the button is cut off by the size of the button in the print window in the Russian version.
**Environment**:Windows 10 build 19042.1288, LazPaint 7.1.6 (64-bit).
**Preconditions**:The program is launched, the Russian language is set.
**Steps to reproduce**:
1.Click on the "Файл" button in the menu bar.
2.In the drop-down menu, click Print.
**Actual result**: The text on the "Увеличить, полностью вписать" button does not fit within the button's size.
**Expected result**: All labels are displayed correctly..
**Attachment**:
![image](https://user-images.githubusercontent.com/93270625/139091906-49214550-4a15-4de5-b0c1-2eb2f928d859.png)

**Comment by circular17** [comment] 2022-05-28 16:37
duplicate of https://github.com/bgrabitmap/lazpaint/issues/412

**Closed by circular17** 2022-05-28 16:37 UTC
