### ISSUE TITLE
The working window of the program goes to the background

### ISSUE THREAD

**Issue by GoncharovaNatalia** [bgrabitmap/lazpaint#336] opened 2021-10-17 18:15 UTC
Full description - When the edit texture window is closed, the working window ceases to be active and goes into the background.
Reproducibility – always. 
Severity – Minor.
Environment – Windows 10 (64-bit), LazPaint 7.1.6 (64-bit)
Steps To Reproduce - Any file is open. Select "texture display", click preview, close the "edit texture" window with a green check mark or a red cross
Additional Information – report3.mp4

https://user-images.githubusercontent.com/92689012/137639749-7c52eeb2-50d6-4864-ae01-c28bda9b12c8.mp4

**Comment by circular17** [comment] 2022-06-04 19:26
Fixed on dev

**Comment by circular17** [comment] 2022-06-04 19:27
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/417

**Closed by circular17** 2022-06-04 19:26 UTC
