### ISSUE TITLE
The text is reflected when the incorrect writing area is specified

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#391] opened 2021-11-18 17:55 UTC
**1.	Summary:** 
The text is reflected when the incorrect writing area is specified
**2.	Description:**
The direction in which the text input area is drawn specifies the orientation of the font. When you create the input area diagonally to the right and down, the text orientation is correct. When you create an input area diagonally to the top right, there is no text. When you create an input area diagonally to the left and up, the font is rotated 180 degrees. When you create an input area diagonally to the left and down, there is no text.
**3.	Steps to reproduce:**

- Select tool Text
- Set the text input area to diagonal right down/diagonal right up/diagonal left up/diagonal left down
- Enter text

**4.	Expected result:**
The text is in the correct orientation anyway
**5.	Actual result:**
The text is oriented correctly/missing/rotated 180 degrees/missing
**6.	Environment:**
Windows 8.1
**7.	Version:**
LazPaint 7.1.6 (64-bit)
**8.	Severity:** 
Minor
**9.	Attachment:**

https://user-images.githubusercontent.com/45390523/142470207-1fd6b73b-fa2d-4c1f-b84d-716bc5f84083.mp4

**Comment by circular17** [comment] 2021-11-28 15:48
that the text would be flipped/rotated is the wanted behavior. however it shouldn't be missing.

**Comment by circular17** [comment] 2022-05-28 16:33
duplicate of https://github.com/bgrabitmap/lazpaint/issues/458

**Closed by circular17** 2022-05-28 16:33 UTC
Labels: bug
