### ISSUE TITLE
Sticky keys "Motion Blur"

### ISSUE THREAD

**Issue by Wixenia** [bgrabitmap/lazpaint#320] opened 2021-10-01 13:47 UTC
Filter -> Motion Blur. When you press it, sticking to the key is periodically triggere

https://user-images.githubusercontent.com/44490229/135630669-674fee1c-8ab2-47f8-a899-e5c0bc688327.mp4

d.

**Comment by circular17** [comment] 2022-06-04 19:34
Thanks for the feedback. What do you mean by sticky keys?

**Comment by circular17** [comment] 2022-06-04 20:19
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/300

**Closed by circular17** 2022-06-04 20:19 UTC
Labels: feedback
