### ISSUE TITLE
Smooth operation when changing the size of the panel of colors and layers.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#432] opened 2021-11-21 10:49 UTC
1) Summary:
Smooth operation when changing the size of the panel of colors and layers.
2) Description:
The application does not run smoothly when changing the width of the colors and layers bar.
  3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- Place the cursor on the left edge of the Colors and Layers panel
- hold down  the left mouse button
- Move cursor from right to left and back

5) Expected behavior
Smooth application work.
6) Actual behavior
the application does not run smoothly.
7) Attachment:

https://user-images.githubusercontent.com/94738204/142758815-84ebc64c-29d6-49d6-8b1b-d556eb13eb70.mp4

8) Severity - Minor
9) Priority- Low

**Comment by circular17** [comment] 2021-11-27 17:04
duplicate of https://github.com/bgrabitmap/lazpaint/issues/384

**Closed by circular17** 2021-11-27 17:04 UTC
