### ISSUE TITLE
The button "Zoom, Fully Fit" the text of the button did not fit completely into the borders of the button

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#489] opened 2022-01-26 10:18 UTC
In the print panel, the button "Zoom, Fully Fit" the text of the button did not fit completely into the borders of the button.
When resizing the print window, the orientation panel does not change, and the "Zoom, Fully Fit" button does not change either.
Partially missing translation in print window.

![Д9_Отсутсвтие перевода окна сохранения](https://user-images.githubusercontent.com/98400320/151145844-e46d3326-bf65-4e3e-8ead-3c7656c0cab9.png)

**Comment by circular17** [comment] 2022-05-27 15:50
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/412

**Closed by circular17** 2022-05-27 15:50 UTC
