### ISSUE TITLE
Incompletely localized interface into Russian

### ISSUE THREAD

**Issue by AntoninaManzhela** [bgrabitmap/lazpaint#353] opened 2021-10-27 11:05 UTC
**Description**
Many settings are not translated into Russian in the menu bar

**Environment**
Windows 10 64-bit
LazPaint 7.1.6 (64-bit)

**Steps to reproduce:**
1 Select edit from menu bar
2 a drop-down window opens

**Expected result**
All settings are translated into Russian

**Actual result**
Several settings are not translated into Russian

![Не доконца локализованный интерфейс](https://user-images.githubusercontent.com/93258577/139053954-97f1ab32-56b6-48db-b290-8b188c49a27e.png)

**Comment by Ser82-png** [comment] 2021-11-01 11:52
The updated Russian translation is not included in the release. Download lazpaint.ru.po and replace yours with it

**Comment by circular17** [comment] 2022-06-04 18:53
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/415

**Closed by circular17** 2022-06-04 18:53 UTC
