### ISSUE TITLE
Translation into Arabic in the menu.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#441] opened 2021-11-28 03:37 UTC
⦁	Summary:
Translation into Arabic in the "View" menu.
⦁	Description:
When opening the menu in the "View" tab in the Arabic version of the application, some item names are not translated into Arabic.
⦁	Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
⦁	Steps to reproduce:
In the program menu, select the "View" tab.
⦁	Expected behavior:
All item names are reflected in Arabic.
⦁	Actual behavior:
Some item names are reflected in English
⦁	Attachment:
![image](https://user-images.githubusercontent.com/95121493/143728038-828da2cb-eb77-40df-a8c9-3a88bc146a40.png) 
⦁	Severity: 
Trivial
⦁	Priority:  
Medium

**Comment by circular17** [comment] 2021-11-28 06:15
If you know Arabic, maybe you can help with the translation. Here are latest version of them:
https://github.com/bgrabitmap/lazpaint/tree/dev-lazpaint/lazpaint/release/bin/i18n

Arabic files have .ar.po extension. You can fill them with a text editor or with a PO editor. To test them, it might be easier to use the portable version and replace the po files in the i18n subdirectory.

You can post a translation here or via a pull request on dev-lazpaint branch.

Note: I will redirect other Arabic translation issues to this one.

**Comment by circular17** [comment] 2022-07-30 19:53
Duplicate of #379

**Closed by circular17** 2022-07-30 19:53 UTC
Labels: feedback
