### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by Wixenia** [bgrabitmap/lazpaint#321] opened 2021-10-01 13:50 UTC
Selecting an area - the tool "Edit Shape" - "Transform Texture" - "Warp Mesh" - this action led to the imposition of several error messages on top of each other, the program crashed, but did not close. Further actions with the program are impossible. Closing the program through the task manager.

https://user-images.githubusercontent.com/44490229/135632763-fab03e0e-621f-451e-aa26-c59b203f73c5.mp4

**Comment by circular17** [comment] 2022-06-04 19:33
I think it is fixed on dev branch

**Closed by circular17** 2022-06-04 19:33 UTC

**Comment by circular17** [comment] 2022-06-04 19:47
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/313
