### ISSUE TITLE
Incorrect display of the image when expanding and decreasing the ‘Dock layers and colors’ panel.

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#406] opened 2021-11-20 13:58 UTC
Priority: MINOR

Environment: Microsoft Windows 7, 6.1.7601 Service Pack 1 (7601), LazPaint 7.1.6(32-bit)

Description:
The user tries to adjust the size of the ‘Dock layers and colors’ panel and the image does not adapt to the new size but is displayed incorrectly.

Steps to reproduce:
2.Move the mouse cursor to the left border of the ‘Dock layers and colors’ panel;
4.Hold down the left mouse button to stretch the cursor in different directions and change the size of the panel.

Actual result: The image stretches behind the panel and displays incorrectly.

Expected result: The image adjusts to the panel changes.

https://user-images.githubusercontent.com/65169031/142728967-3193f55f-48f8-46da-92bb-d8a6d33f780f.mov

**Comment by circular17** [comment] 2021-11-28 06:56
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/384

**Closed by circular17** 2021-11-28 06:56 UTC
