### ISSUE TITLE
«Zoom to fit in the window» doesn't work correctly

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#396] opened 2021-11-18 18:33 UTC
**1.	Summary:** 
«Zoom to fit in the window» doesn't work correctly
**2.	Steps to reproduce:**

- Select «Zoom to fit in the window»

**3.	Expected result:**
The whole image fits into the size of the workspace
**4.	Actual result:**
The image is resized to fit the workspace, but not centered
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor
**8.	Attachment:**

https://user-images.githubusercontent.com/45390523/142475754-618f71ed-8f42-4612-af05-139445929c84.mp4

**Comment by circular17** [comment] 2022-06-04 18:33
duplicate of https://github.com/bgrabitmap/lazpaint/issues/405

**Closed by circular17** 2022-06-04 18:33 UTC
