### ISSUE TITLE
Minimizing LazPaint when close the "Edit selection" window

### ISSUE THREAD

**Issue by diatarveden** [bgrabitmap/lazpaint#506] opened 2022-03-30 12:30 UTC
**Description:**

> LazPaint minimizes after close the "Edit selection" window

**Step of reproduction:**

> 1. Open LazPaint
> 2. Go to ''Select'' -> ''Edit selection''
> 3. Close "Edit selection" window

**Expected result:**

> The Edit Selection window will close, LazPaint will remain maximized

**Actual result:**

> The Edit Selection window will close, LazPaint minimizes

**Environment:**

> Windows 10 x64, Build 19042.1586, Version 20H2
> LazPaint 7.1.6, 64-bit

**Severity:**

> Minor

**Priority:**

> Medium

**Comment by fozkan** [comment] 2022-05-25 20:31
In LazpaintMainForm unit onHide Event
`  FShouldArrange := false;
  //FTopMostInfo := LazPaintInstance.HideTopmost; // Commenting This line
  LazPaintInstance.SaveMainWindowPosition;`

commenting `FTopMostInfo := LazPaintInstance.HideTopmost;` solves the problem.

**Comment by circular17** [comment] 2022-05-28 22:35
Thanks for the feedback.

The suggested line to comment is useful to hide and restore tool windows when minimizing LazPaint.

This issue is a duplicate of https://github.com/bgrabitmap/lazpaint/issues/417

It was solved by bringing to front the main window after editing the selection.

**Closed by circular17** 2022-05-28 22:35 UTC
