### ISSUE TITLE
Zoom to fit in the window(AlT+F) work strangly

### ISSUE THREAD

**Issue by YuriyZubko** [bgrabitmap/lazpaint#346] opened 2021-10-19 13:54 UTC
1. Description
When you click on button "Zoom to fit in the window"/(AlT+F) sometimes this function zoom picturs on left/right side of display
2. Environment
Windows 10 Build 19043.1288
LazPaint ver 7.1.6.0 RU version
3. Steps to reproduce
1. Create new project
2. Click on  "Zoom to fit in the window" or press AlT+F
3. Drag the layer on any direction
4. Change percentage on zoom
5. Click on  "Zoom to fit in the window" or press AlT+F
4. Expected result
center alignment of the image
5. Actual result
Change zoom only
6. Attachment

https://user-images.githubusercontent.com/92620013/137924477-2783178d-028f-446e-b686-ccc54559bfbe.mp4

**Comment by circular17** [comment] 2022-06-04 11:21
duplicate of https://github.com/bgrabitmap/lazpaint/issues/405

**Closed by circular17** 2022-06-04 11:21 UTC
