### ISSUE TITLE
Does not fit text in the button in "Print" menu

### ISSUE THREAD

**Issue by YuriyZubko** [bgrabitmap/lazpaint#344] opened 2021-10-19 12:36 UTC
**1.     Description**
 When you click on "Print" menu "Увеличить полностью вписав" doe not fill completly in the box.
**2.	Environment**
Windows 10 Build 19043.1288
LazPaint  ver 7.1.6.0 RU version
**3.	Steps to reproduce**
Click on print menu or click "Ctrl+P" 
**4.	Expected result**
Correct text in the button
**5.	Actual result**
Text not fit in the button
**6.	Attachment**
![incorrectzoommessage](https://user-images.githubusercontent.com/92620013/137910147-999a471f-5353-4697-9495-b3b091f09a07.PNG)

**Comment by circular17** [comment] 2022-05-28 16:35
duplicate of https://github.com/bgrabitmap/lazpaint/issues/412

**Closed by circular17** 2022-05-28 16:35 UTC
