### ISSUE TITLE
"Zoom fit" function does not work correctly

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#433] opened 2021-11-21 10:50 UTC
1) Summary:
  "Zoom fit" function does not work correctly
2) Description:
The user clicks the "Zoom fit" button and gets an image that can fit into the work area, but it is not positioned correctly.
  3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- select the "View" tab in the menu and click on the "Zoom fit" item, or on the top panel click the "Zoom fit" button

5) Expected behavior
The image is displayed in full.
  6) Actual behavior
The image is not fully visible in the work area.
7) Attachment:

https://user-images.githubusercontent.com/94738204/142758859-38e8f930-84db-4948-9272-9fc0d0202702.mp4

8) Severity - Major
9) Priority- High

**Comment by circular17** [comment] 2021-11-28 06:41
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/405

**Closed by circular17** 2021-11-28 06:41 UTC
