### ISSUE TITLE
Ideas to make LazPaint useful for making meme captions 

### ISSUE THREAD

**Issue by LinuxBeaver** [bgrabitmap/lazpaint#245] opened 2021-03-27 20:42 UTC
Hello, I don't really know if this is your vision for Lazpaint.  But in the world of open source we don't really have a offline usable GUI tool that can straight forwardly make quick captions on images, but LazPaint comes really close to perfecting this. I would like to share three major ideas on how LazPaint can improve.

![image](https://user-images.githubusercontent.com/78667207/112733346-768f2d00-8f37-11eb-90cf-e6d539765122.png)

**1.** LazPaint could benefit from the ability to space text. Such as the ability to space text horizontally and vertically
 
Horizontal Spacing
![image](https://user-images.githubusercontent.com/78667207/112733602-d934f880-8f38-11eb-91a6-3314ba02c409.png)

Horizontal and Vertical Spacing
![image](https://user-images.githubusercontent.com/78667207/112733609-e94cd800-8f38-11eb-9e2d-d7a275da1550.png)

It would also need a button to reset spacing to default. 

**2.** LazPaint's Align Shape tool and alt Arrow shortcuts to access it are very useful, but if it had a key binding and or button that automatically aligned text to the center that would be even better for making captions. For example, No matter where a shape, selection or text is on screen. If it is applied vertically and horizontally it will be be in dead the center of the screen. From there tightly selected text can be positioned on the top, center or bottom of the screen via alt arrow keys.

If a command existed that  applied "Center Shape Horizontally" and "Center Shape vertically" together, that would be a huge  help

**3.** The ability to copy everything onto the clipboard. Some graphical programs like "Gimp and Pixelitor" have a Ctrl Shift C option to copy all data from all layers to the clipboard. This would be very useful for copying a meme or anything to a clipboard and pasting it into a website, file managers or other applications that support copy paste.

-
These are the three things I think Lazpaint would need to tackle for it to improve in these areas. Also, I find it really impressive Lazpaint can already make gradient text, bevel text and editable rotated text. Gimp is really behind in this area and doesn't even have vector layers.

**Comment by circular17** [comment] 2022-05-28 15:37
Thanks for the suggestions.

1. Duplicate of https://github.com/bgrabitmap/lazpaint/issues/119
2. Done on dev: Alt-H and Alt-V to center. Also added vertical align of text
3. Not sure how to copy all things as the clipboard just contain one image, or maybe I am missing something?

Thanx for the love. It was a big challenge to do all these text features, but I am very happy I've done it!

Regards

**Closed by circular17** 2022-05-28 15:37 UTC
