### ISSUE TITLE
Incorrect selected language after cancel the "Exit request" window

### ISSUE THREAD

**Issue by diatarveden** [bgrabitmap/lazpaint#502] opened 2022-03-29 09:53 UTC
**Description:**

> After change the interface language and click "Cancel" in the "Request Exit" window, the checkbox of language has changed.

**Step of reproduction:**

> 1. Open LazPaint
> 2. Draw something by the pen tool
> 3. Go to "File" -> "Language", click any unselected language
> 4. In the "Exit request" window select "Cancel"
> 5. Go to "File" -> "Language"

**Expected result:**

> The selected will be the language with which LazPaint was launched

**Actual result:**

> The selected language chosen in step 3 of the "Step of reproduction" section

**Environment:**

> Windows 10 x64, Build 19042.1586, Version 20H2
> LazPaint 7.1.6, 64-bit

**Severity:**

> Minor

**Priority:**

> Low

**Attachment:**

https://user-images.githubusercontent.com/102584378/160573383-c885b156-dac1-4857-8817-eb8de1a1f972.mp4

**Comment by circular17** [comment] 2022-05-27 12:15
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/430

**Closed by circular17** 2022-05-27 12:15 UTC
