### ISSUE TITLE
Missing tool group images in toolbar on hover

### ISSUE THREAD

**Issue by GrampusV** [bgrabitmap/lazpaint#473] opened 2022-01-24 11:58 UTC
**Description:**
Missing tool group images in toolbar on hover

**Steps to reproduce:**
1. Launch the application
2. Move the mouse cursor over the tool group in the toolbar

**Actual result:**
There aren't some items in the toolbar

**Expected result:**
All tools and their groups have a graphic image

**Comment:**
This problem occurs intermittently, but not constantly.

**Environment:**
- OS: MacOS Catalina Version 10.15.7
- Software: LazPaint 7.1.6 (64-bit)

![photo_2022-01-24_17-53-30](https://user-images.githubusercontent.com/22413436/150778946-27cc4645-b21f-4e7e-97ab-9e5ad957af18.jpg)

**Comment by circular17** [comment] 2022-05-28 16:26
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/472

**Closed by circular17** 2022-05-28 16:26 UTC
