### ISSUE TITLE
The Edit texture window disappears when minimized

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#393] opened 2021-11-18 18:05 UTC
**1.	Summary:** 
The Edit texture window disappears when minimized
**2.	Description:**
A minimized window does not appear in the taskbar. The main program window is inactive. You can open the window via Alt + Tab. 
**3.	Steps to reproduce:**

- Open the Edit texture window
- Click Minimize button

**4.	Expected result:**
The Edit texture window is minimized
**5.	Actual result:**
The Edit texture window disappears. The main program window is inactive
**6.	Environment:**
Windows 8.1
**7.	Version:**
LazPaint 7.1.6 (64-bit)
**8.	Severity:** 
Major

**Comment by circular17** [comment] 2022-06-04 18:36
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/418

**Closed by circular17** 2022-06-04 18:36 UTC
