### ISSUE TITLE
"Fast Blur" issue

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#283] opened 2021-09-10 15:06 UTC
Pixel band (at top of the image workspace) remains not blurred after using the blur "Fast Blur".
![image24](https://user-images.githubusercontent.com/90435360/132875358-2a3564ec-4573-4725-adc4-f07467d431fb.png)

**Comment by circular17** [comment] 2022-05-28 17:09
I cannot reproduce the problem. It may be fixed on dev. Also this may be only a display issue. After moving the image around and zooming in, it may appear blurred.

**Closed by circular17** 2022-05-28 17:09 UTC
