### ISSUE TITLE
Incorrect display of the image when pressing the ‘Zoom fit' button.

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#405] opened 2021-11-20 13:45 UTC
Priority: MINOR

Environment: MacOS Big Sur 11.5.1(20G80), LazPaint 7.1.6 (64-bit)
AND 
Microsoft Windows 7,6.1.7601 Service Pack 1 (7601),LazPaint 7.1.6(32-bit)

Description:
The user presses ‘Zoom fit’ button and receives an incorrect image that doesn’t fit the window.

Steps to reproduce:
2.Click on the button ‘View’ on the top panel of the app;
4.In the menu that appears, choose the ‘Zoom fit’ button.

Actual result: The user receives an un-centered image by clicking ‘Zoom fit’.‘Zoom fit’ place picture on the left side of the window.

Expected result: The user receives a correctly scaled image that fits to the size of the window by clicking ‘Zoom fit’

https://user-images.githubusercontent.com/65169031/142728584-29155945-c978-474f-9085-47a6d37e9917.mov

.

https://user-images.githubusercontent.com/65169031/142728596-e6279267-a001-4213-a8e2-f300edc111b7.mov

**Comment by circular17** [comment] 2021-11-28 06:41
Indeed image is not centered

**Comment by circular17** [comment] 2022-06-04 21:50
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/248

fixed on dev

**Closed by circular17** 2022-06-04 21:50 UTC
Labels: bug
