### ISSUE TITLE
Keyboard shortcuts do not work with the Russian keyboard layout

### ISSUE THREAD

**Issue by Badchaos11** [bgrabitmap/lazpaint#488] opened 2022-01-26 10:18 UTC
Description: With Russian layout shortcuts don’t work or cause incorrect functions.

Steps to reproduce:
1.	Open LazPaint;
2.	Open Tools menu;
3.	Use any hot key (for example G).

Expected result: Tool changes on gradient, floodfill or shaded shape.
Actual result: Tool changes on Pen or Edit shape.

https://user-images.githubusercontent.com/98452721/151146844-13934499-f611-4f9d-a346-6c52489def51.mp4

**Comment by circular17** [comment] 2022-05-28 23:13
duplicate of https://github.com/bgrabitmap/lazpaint/issues/503

**Closed by circular17** 2022-05-28 23:13 UTC
