### ISSUE TITLE
Fails to start on NixOS - Unhandeled exception: Access violation

### ISSUE THREAD

**Issue by onny** [bgrabitmap/lazpaint#515] opened 2022-08-07 09:02 UTC
Currently I'm trying to package `lazpaint` 7.2 together with latest bgrabitmap (11.5.1) and bgracontrols (7.6) https://github.com/NixOS/nixpkgs/pull/181093 When trying to start `lazpaint` I get an empty Window and an error message popup
```
Unhandled exception!

Exception class: EAccessViolation
Message: Access violation
To get more information, use the debug version.

It is recommended to save a backup of your image and restart the application.
```
What is the best way to debug this?

Best regards
Jonas

**Comment by rchastain** [comment] 2022-08-07 09:40
Hello! I would begin to change the build mode (in project options/compiler options) to 'Debug'. And I would start LazPaint from a terminal.

**Comment by circular17** [comment] 2022-08-07 14:50
This would give indeed more detail on the error.

**Comment by circular17** [comment] 2022-08-19 13:27
Hello, I've tried a virtual machine on VirtualBox, but I don't know how to install packages. I tried the command "nix-env -qaP"  but doesn't show anything and gets stuck
<img width="240" alt="nix-env_stuck" src="https://user-images.githubusercontent.com/9092455/185628711-911af9b1-01a5-49ec-8fd5-022d8cdb8f03.png">

**Comment by onny** [comment] 2022-08-19 13:31
Thank you for trying to investigate. This is what you can do:

```
git clone git@github.com:onny/nixpkgs.git
cd nixpkgs
git checkout lazpaint
nix build -f . lazpaint
```

This will build lazpaint including its dependencies from this PR https://github.com/NixOS/nixpkgs/pull/181093

**Comment by circular17** [comment] 2022-08-19 17:05
Thanks but I need to install Lazarus to debug the program. I don't understand how to use NixOS, maybe it doesn't work on my VirtualBox. It is very slow, maybe that's why it gets stuck?

**Comment by circular17** [comment] 2022-08-23 08:21
@onny I tried to do the method your suggest, but it doesn't recognize "git" command:
<img width="530" alt="Capture d’écran 2022-08-23 à 10 17 52" src="https://user-images.githubusercontent.com/9092455/186108739-afea28fe-e5bc-4ab3-baaf-96500478aa7c.png">

Trying to install git does nothing, it gets stuck until I press Ctrl-C or Ctrl-Z:
<img width="311" alt="Capture d’écran 2022-08-23 à 10 20 05" src="https://user-images.githubusercontent.com/9092455/186109017-beea354a-8fc6-4cbb-8686-01e4beb71392.png">

**Comment by circular17** [comment] 2022-08-23 08:21
Note: I am using the demo virtual machine provided on NixOS website.

**Comment by circular17** [comment] 2022-10-09 07:40
Oh I found how to install package. To get the command you need to go to the website https://search.nixos.org/packages

There you can type the name and in the "nix-env" tab, there is the command to install:
<img width="907" alt="search-git-package" src="https://user-images.githubusercontent.com/9092455/194743989-3a023bff-a51b-49a3-899b-ff8081dd8ea9.png">

There is also Lazarus 2.0.12.

**Comment by circular17** [comment] 2022-10-09 08:25
I was not able to reproduce the exception by compiling it with Lazarus 2.0.12 and running it in debug mode.

I thought I would try with the debug version I made recently:
https://github.com/bgrabitmap/lazpaint/releases/download/v7.2.2/lazpaint7.2.2_linux64_gtk2_debug.tar.gz

Though from the file explorer, double-clicking or choosing Launch on the binary "lazpaint" has no effect.

From the command line, it doesn't work either:
<img width="730" alt="run-from-commandline" src="https://user-images.githubusercontent.com/9092455/194746077-38e2ea0e-9631-4ddb-9c33-f64ba7840792.png">

**Comment by nyx191** [comment] 2023-12-25 07:00
Same for me, Debian trixie, 7.2.2-2.
Debian provides lazpaint-gtk2 and lazpaint-qt5. Can reproduce with QT5 version. No error with GTK2.

**Comment by circular17** [comment] 2023-12-25 23:41
Hello @nyx191, thanks for popping by.

It could help pinpoint exactly where there error happens by running the program in debug mode, either with debug binaries (though I've had no luck doing so) or from the development environment (Lazarus):
https://wiki.freepascal.org/LazPaint#Compilation_of_latest_version

Regards

**Comment by circular17** [comment] 2023-12-28 16:16
Hi @nyx191 

Thanks for taking the time to compile the program. It seems you've encountered errors along the way.

From the stack trace, I gather that a timer is triggered too soon. I've applied a fix to prevent that on the `master` branch. This won't be included in the zip file in the release folder, but the `master` branch is basically the latest version.

About the errors you got during the compilation, the _Makefile_ indeed is not designed to build the debug version. It will indeed consider that it fails because it won't find the binary in the _release_ folder.

To make the debug version, I usually open Lazarus development environment and choose the build mode from there. Though it is possible to do that using the command line, as you actually did by tweaking the _Makefile_.

The actual command to make the debug binaries is:
```bash
lazbuild -B -r --build-mode=$(BUILDMODE) $(FOREIGN_PACKAGES) lazpaintcontrols/lazpaintcontrols.lpk lazpaint/lazpaint.lpi
```

Where
- `$BUILDMODE` is `Debug`, `DebugQt5` or `"Debug macOS"` when applicable.
- `$FOREIGN_PACKAGES` is the full path of BGRABitmapPack and BGRAControls when those packages are not already known by _lazbuild_.

This will put the resulting binary in a subfolder of the _debug_ folder as you found out.

**Comment by nyx191** [comment] 2023-12-28 17:48
Tested your patch, it works. Hope it will eventually get into Debian, with next release I guess.
Thank you very much for the fix! Saved convenient command, so now I am able to build things with Lazarus.
I think that issue can now be closed.

**Comment by circular17** [comment] 2023-12-28 18:32
That's great to hear.

I've pushed the change into the upstream repository and contacted the Debian maintainer. This is not a new release as such.
https://github.com/bgrabitmap/lazpaint-upstream

I will make a new release at some point for various reasons, and of course the fix will be included.

Thanks again for your detailed feedbacks.

**Closed by circular17** 2023-12-28 18:32 UTC
Labels: bug
